version: '3'

services:
  api:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.20'
          memory: 20M
    command: sh -c "sleep 15 && npm run start"

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - dbdata:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
        reservations:
          cpus: '0.20'
          memory: 50M
    networks:
      - backend

  db-seed:
    build: ./data
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  dbdata:
  node_modules: